### ISSUE TITLE
Forgot running app:import:trans?

### ISSUE THREAD

**Issue by fafranco82** [Alsciende/thronesdb-json-data#145]
Spanish translation of Guarding the Realm is not being shown yet... did you forget running the import trans command after that? Or simply you were (and are) very busy these days? Or just both of them XD.

It's only a question, I don't mean to rush you, take your time ;-) :-)

**Comment by Alsciende** [comment]
I did run it, but it's not working for whatever reason. I'm investigating...

**Comment by Alsciende** [comment]
Fixed!

**Comment by fafranco82** [comment]
Thanks a lot!
