### ISSUE TITLE
Schema inconsistency between main schema and translation schema for `flavor`

### ISSUE THREAD

**Issue by ystros** [Alsciende/thronesdb-json-data#229]
In the main schema, the `flavor` property can either be a string (empty or otherwise) OR simply `null`. However, in the translation schema, the `flavor` property can only be a string. In both cases, it's an optional property.

This leads to errors where this is valid for the main data file:
```
{
  // ...
  "flavor": null,
  // ...
}
```

but when copied over to a translation file, will fail validation.

It's not 100% clear to me whether this was an intentional design decision or if something that just got out of sync over time. I'd suggest that since `flavor` is already optional, null doesn't need to be an allowed value in either schema, but maybe there's a reason behind allowing it.

**Comment by fafranco82** [comment]
It seems a change in the main schema not propagated to translation schema... `null` (or empty string) was not allowed before both for `flavor` and `text` properties, but now `flavor` can be empty or null and `text` can be empty (but not null), also changed from optional to required. The latter was because of this: https://github.com/Alsciende/thronesdb/issues/94.

But I don't remember why `flavor` constraints were changed...

I will add to the pending PR the fix for this and formatting issues (I forgot to use the validator!! shame on me!)

**Comment by Alsciende** [comment]
`flavor` should be like `text` in the databaseS: not nullable. The reason is the same for both: if a user wants to find all cards that don't include a given string in their text or flavor field, that field must not be nullable.

**Comment by fafranco82** [comment]
So `flavor` must be an empty string when card has no flavor text, doesn't it?

**Comment by Alsciende** [comment]
Yes. But the json data could still be nullable/optional, as long as the importer can convert a null value to an empty string.

**Comment by Alsciende** [comment]
Obviously it will be easier for me if the flavor field is not optional, like the text field. But with some many cards having no flavor field, it's annoying to make it mandatory.

**Comment by Alsciende** [comment]
@fafranco82 @ystros do you mind if I change `flavor` to be mandatory? I have the commit ready to align the json data.

**Comment by fafranco82** [comment]
I don't mind at all ;)

**Comment by ystros** [comment]
It seems somewhat strange to me to make `flavor` a mandatory field when so many instances will be blank. It seems like making it non-nullable but still optional, and defaulting it to empty string when importing into the database if the field is missing would keep the JSON data more "pure" and compact.

But if it makes things easier for you to make it required in the data, please go ahead. 👍
