### ISSUE TITLE
Data representation related to Shadows cards

### ISSUE THREAD

**Issue by ystros** [Alsciende/thronesdb-json-data#241]
I have a partial data implementation for the announcement of The Shadow City pack:
https://www.fantasyflightgames.com/en/news/2018/2/21/the-shadow-city/
https://github.com/Alsciende/thronesdb-json-data/compare/master...ystros:the-shadow-city-announcement?expand=1

However, there are 2 data schema problems I'd like to discuss before PRing.

1. From a data perspective, should the new "Shadow" sigil on gold cost from the cards be represented by a boolean flag on card data (e.g. `is_shadow`)?  My first impression is that it should not be represented, since it only appears (so far) on cards that also have the new Shadow keyword and is therefore merely decorative. It could potentially useful in terms of search (though users could easily just search for `x:Shadow` instead), but I'd hate to add a new required field to all cards for something that will only apply to a small subset.

2. The [Beneath the Bridge of Dreams](https://images-cdn.fantasyflightgames.com/filer_public/90/c5/90c5cef9-3012-4b02-a626-36c2c8fd7780/gt31_beneath-the-bridge-of-dream.png) presents somewhat of a schema dilemma. It has no cost, it must be put into shadows, then can be brought out of shadows for free. The gold cost on the card is marked as "-". Normally, I'd represent this using a `null` cost. However, `null` cost is currently being used to represent cards that cost X, such as The Hand's Judgment. It could be represented with 0 cost, but that's not quite correct either. So we need some way to distinguish between 0 cost, X cost, and - cost cards.

Thoughts?

**Comment by Alsciende** [comment]
1. I agree with you that a dedicated attribute for shadow cards doesn't seem to be necessary.

2. Maybe it's time to bite the bullet and change the type of the cost attribute to string instead of integer. There's no benefit to having an integer, except for sorting. Since all the costs are smaller than 10, we can sort costs as strings anyway. Then null can be used for cards with no cost, such as **Beneeath the Bridge of Dreams**, agendas and plots.

**Comment by Alsciende** [comment]
Actually there's a benefit to having an integer. Users can query for cards with cost lesser or greater than a number. It won't be as simple if cost is a string. I'm going to see if cost can be stored as a string but used as an integer, and how `X` will be handled.

**Comment by Alsciende** [comment]
I made the necessary changes in https://github.com/Alsciende/thronesdb/pull/187 and https://github.com/Alsciende/thronesdb-json-data/pull/242. I'll just wait for your feedback before merging.

**Comment by ystros** [comment]
Closing since #242 has been merged.
