### ISSUE TITLE
Rulebook

### ISSUE THREAD

**Issue by mplain** [Alsciende/thronesdb-json-data#26]
Please add an html version of the RRG to the website.

If there's any more work needed to be done on it, I'm ready and willing to help.

**Comment by Alsciende** [comment]
I didn't proceed with your Rulebook because there's still too much work to do with the Timing Chart. I tried to fix the formatting, but it's quite difficult to render that chart in simple html.

**Comment by mplain** [comment]
Maybe for now just replace text with this picture?
https://drive.google.com/file/d/0B7h7ITS96lIYZjNBRWNrSnNSams/view

You cannot copy text from it, but it's still very useful.

**Comment by Alsciende** [comment]
Why not, yes. That's an easy solution.

![rr1](https://cloud.githubusercontent.com/assets/391974/16271568/d8f2d68e-389a-11e6-8a85-e9aedf7ec0cc.png)
![rr2](https://cloud.githubusercontent.com/assets/391974/16271571/de5260cc-389a-11e6-95a4-1675acc40f76.png)
![rr3](https://cloud.githubusercontent.com/assets/391974/16271575/e25411ac-389a-11e6-9dbe-7d20fa5b04b3.png)
![rr4](https://cloud.githubusercontent.com/assets/391974/16271577/e41bc3fe-389a-11e6-9338-3af64934ddc6.png)
![rr4b](https://cloud.githubusercontent.com/assets/391974/16271580/e603a218-389a-11e6-8f53-b6903e7cd1c2.png)
![rr5](https://cloud.githubusercontent.com/assets/391974/16271583/e80250fa-389a-11e6-93a4-f8c2ec29c3f2.png)
![rr6](https://cloud.githubusercontent.com/assets/391974/16271584/e9c706c4-389a-11e6-94e5-bb4f155fb6ca.png)
![rr7](https://cloud.githubusercontent.com/assets/391974/16271587/ec7d114c-389a-11e6-8ec2-480761fd041a.png)

**Comment by mplain** [comment]
I am in doubt, not sure why you attached the images, do you want me to insert them into the html file and submit it to you? Or was it for your own convenience?

**Comment by Alsciende** [comment]
It's ok, I just attached them to make sure I'll have them later :) I'll try to set up the rulebook asap.

**Comment by Alsciende** [comment]
Done :-)

**Comment by mplain** [comment]
Cool, thanks! :)
I'll get to working on the FAQ then!

You put in-text icons in place of graphic icons, and [text] in place of in-text icons - is that intentional? Don't want to put pictures on this page?

Regarding the Timing Sequence Chart. Personally, I feel like a single .jpg that I provided would be more clean/neat than several separate images. As it is now, you have to scroll down several pages. Also, it's not printer-friendly. Users could just print the single .jpg for easy reference.

Greak work with tagging all the Related keywords! Thanks! :)

**Comment by Alsciende** [comment]
I prefer the icons that way. I don't want raster image icons. So I adapted when needed (no loyal faction icons).

I also prefer the chart that way. Smaller images can be read more easily on mobile. The total height is the same anyway. I don't think printing is relevant, and users can still print those images anyway.
