### ISSUE TITLE
Search page

### ISSUE THREAD

**Issue by mplain** [Alsciende/thronesdb-json-data#27]
Several suggestions for improving the Card Search page, for when you have some extra time.

1) Clicking on a Faction button should hard-select only this faction, rather than inverting the selection. Normally people who use this function want to narrow their search down to one or two factions, not exclude. Inverting selection could be done with Shift+click.

2) Selecting Type could also be done in the form of buttons. Since there are only ever going to be 7 cardtypes, and all of them (except for Titles) already have icons associated with them on the website.

3) Selecting Loyal, Unique, and Challenge Icons would also be easier to use as buttons. Preferrably 3-position buttons (e.g. plain symbol for Any, with a green check mark for Yes, with a red cross for No). 

4) Same could be done for Numeric values (a 3-position button in the form of a corresponding icon, with a =, <, or > symbol on it). Basically, buttons are quicker and easier to use than drop-down fields.

5) In the Set selection, preferrably sort sets in the same order as when clicking Cards in the orange header.

6) Not sure if the Quantity field is worth having. Maybe change it for Plot Deck Limit 1/2 ?

Thank you!

**Comment by Alsciende** [comment]
Wrong repository :(

**Comment by Alsciende** [comment]
4 issues in the wrong repository :(

**Comment by mplain** [comment]
Sorry, which repo would be the right one for this kind of thing?

**Comment by Alsciende** [comment]
This repo is only for the cards data.

That repo is for the website : https://github.com/Alsciende/thronesdb

But nevermind for those 4 issues. I'll fix them or close them here. No need to recreate them.
