### ISSUE TITLE
Card images with better quality from official FFG previews (no watermarks)

### ISSUE THREAD

**Issue by mplain** [Alsciende/thronesdb-json-data#65]
Got 102 official previews from the FFG website, plus 31 images sent by FFG to various podcasts - all of these images have no watermarks.

https://drive.google.com/open?id=0Bxj6uOtUFSG9MDBaUENhS2s0ejg

**Comment by Alsciende** [comment]
I gave you access to the repository of images. Feel free to replace the watermarked images as you see fit.

**Comment by mplain** [comment]
It's been half an hour and I still can't figure out how to upload pictures on BitBucket. Could you give me a hint?

**Comment by mplain** [comment]
I think I figured it out, the images are there, but they don't show up on ThronedDB. Should I wait for the server to update, or you need to upload the images manually, or did I do something wrong?

**Comment by Alsciende** [comment]
I need to update the server manually. I'll do it later.
